version: '3.7'

services:
  zeeves-site:
    image: ${IMAGE_TAG}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: start-first
      restart_policy:
        delay: 1s
        condition: any
    networks:
      - zeevesnet

networks:
  zeevesnet:
    external: true
